app/models.py
from .db import db


class Dataset(db.Model):
    __tablename__ = "datasets" # будет использовать это имя таблицы в БД
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), unique=True, nullable=False)

    # связь OtM, с обратной связью
    datapoints = db.relationship('DataPoint', backref='dataset', lazy=True)


class DataPoint(db.Model):
    __tablename__ = "datapoints"
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.Integer)
    emg1 = db.Column(db.Integer)
    emg2 = db.Column(db.Integer)
    emg3 = db.Column(db.Integer)
    emg4 = db.Column(db.Integer)
    angle = db.Column(db.Integer)

    # колонка на Dataset, не сможет записать несуществующий datasets.id'
    dataset_id = db.Column(db.Integer, db.ForeignKey('datasets.id'))


class DatasetStats(db.Model):
    __tablename__ = "dataset_stats"
    id = db.Column(db.Integer, primary_key=True)
    dataset_id = db.Column(db.Integer, db.ForeignKey("datasets.id"), unique=True)
    mean = db.Column(db.Float)
    max = db.Column(db.Float)
    std = db.Column(db.Float)
    peaks = db.Column(db.Integer)
    plot_html = db.Column(db.Text)

    # связь 1к1 uselist=False делает связь одиночной, а не списком (в отличие от .datapoints)
    dataset = db.relationship("Dataset", backref=db.backref("stats", uselist=False))

app/__init__.py
from flask import Flask
from .config import Config
from .db import db
from .routes import bp


# создание приложения, разовая миграция, париснг конфигов в словарь фласка
def create_app():
    app = Flask(__name__, template_folder='../templates/')
    app.config.from_object(Config)

    db.init_app(app)
    app.register_blueprint(bp)

    with app.app_context():
        from . import models
        db.create_all()

    return app

app/routes.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from .models import Dataset
from .utils import import_dataset_from_excel


bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    datasets = Dataset.query.all()
    return render_template("index.html", datasets=datasets)


@bp.route("/dataset/<int:dataset_id>")
def view_dataset(dataset_id):
    dataset = Dataset.query.get_or_404(dataset_id)
    if not dataset.stats:
        return "Статистика ещё не рассчитана", 400

    return render_template(
        "dataset.html",
        dataset=dataset,
        stats={
            "mean": dataset.stats.mean,
            "max": dataset.stats.max,
            "std": dataset.stats.std
        },
        peaks=dataset.stats.peaks,
        plot_div=dataset.stats.plot_html
    )


@bp.route("/upload", methods=["POST"])
def upload():
    file = request.files["file"]
    name = request.form["name"]
    save_path = os.path.join(current_app.config["UPLOAD_FOLDER"], f'{name}_{file.filename}')
    file.save(save_path)

    import_dataset_from_excel(save_path, name)
    return redirect(url_for("main.index"))

main.py
from app import create_app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>EMG Data App</title>
</head>
<body>
<header>
    <h1>EMG Анализатор</h1>
    <form action="{{ url_for('main.upload') }}" method="post" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="Название набора" required>
        <input type="file" name="file" accept=".xlsx" required>
        <button type="submit">Загрузить Excel</button>
    </form>
    <hr>
</header>

{% block content %}{% endblock %}
</body>
</html>

templates/dataset.html
{% extends 'base.html' %}

{% block content %}
<h2>Набор: {{ dataset.name }}</h2>
<p>Среднее значение: {{ stats.mean }}</p>
<p>Максимум: {{ stats.max }}</p>
<p>Стандартное отклонение: {{ stats.std }}</p>
<p>Количество пиков (angle > 20): {{ peaks }}</p>
<hr>
<div>{{ plot_div | safe }}</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Доступные наборы данных:</h2>
<ul>
    {% for ds in datasets %}
    <li><a href="{{ url_for('main.view_dataset', dataset_id=ds.id) }}">{{ ds.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}